lingerie_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.http import HttpResponse


urlpatterns = [
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'', include('lingerie_app.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^payments/', include('payments.urls')),
    url(r'^profiles/', include('profiles.urls')),
    # url(r'^dashboard/', include('admin_dashboard_panel.urls')),
    url(r'^robots.txt', lambda x: HttpResponse("User-agent: *\nDisallow:/admin\nAllow:/", content_type="text/plain"),name="robot_file"),

    # Django admin
    url(r'^admin/', admin.site.urls),
]

payments/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='payments_index'),
    url(r'^payment-return/$', views.payments_return, name='payments_return'),
    url(r'^payment-cancel/$', views.payments_cancel, name='payments_cancel'),
    url(r'^payment-notifications/$', views.payments_notification, name='payments_notification'),
    url(r'^payment-admin/$', views.payments_admin, name='payments_admin')
]

payments/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _
from django.db.models.signals import post_save
from django.dispatch import receiver

from products_catalog.models import Product


class CreditCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card_id = models.CharField(max_length=256, null=False)
    card_exp_month = models.CharField(max_length=2, null=False)
    card_exp_year = models.CharField(max_length=4, null=False)

    def __unicode__(self):
        return unicode(self.card_id)

    def __str__(self):
        return str(self.card_id)


class Payment(models.Model):
    user = models.ForeignKey(User)
    credit_card = models.ForeignKey(CreditCard, null=True)
    processing_start_date = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField(default=0)
    currency = models.CharField(max_length=5, null=False, default='EUR')
    payment_id = models.CharField(max_length=256)
    payment_state = models.CharField(max_length=256)
    payment_date = models.DateTimeField(null=True, auto_now_add=True)
    # Status
    STATUS = (
        (0, _('New')),
        (1, _('Sent for processing')),
        (2, _('Payed')),
        (3, _('Error'))
    )
    # 0 - new
    # 1 - sent for processing
    # 2 - payed
    # 3 - error
    status = models.PositiveIntegerField(choices=STATUS, default=0, blank=False)
    TYPES = (
        (0, _('Charge')),
        (1, _('Refund'))
    )
    type = models.PositiveIntegerField(choices=TYPES, default=0, blank=False)


class ClientChargeAmount(models.Model):
    amount_to_charge = models.IntegerField(verbose_name=_('client charge amount'), unique=True)

    def __unicode__(self):
        return unicode(self.amount_to_charge)

    def __str__(self):
        return str(self.amount_to_charge)


class Basket(models.Model):
    payment = models.ForeignKey(Payment, related_name='payment')
    STATUS = (
        (0, _('shopping	time')),
    )
    status = models.PositiveIntegerField(choices=STATUS, default=0, blank=False)
    products = models.ManyToManyField(Product, blank=True)

    def __unicode__(self):
        return unicode('Basket for {} {}'.format(self.payment.user.first_name, self.payment.user.last_name))

    def __str__(self):
        return str('Basket for {} {}'.format(self.payment.user.first_name, self.payment.user.last_name))


@receiver(post_save, sender=Payment)
def create_user_basket(sender, instance, **kwargs):
    Basket.objects.get_or_create(
        payment=instance,
        status=0
    )

payments/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.contrib.auth.models import User


class AdminPaymentForm(forms.Form):
    user = forms.ModelChoiceField(queryset=User.objects.all().only('id', 'first_name'))
    amount = forms.FloatField(label='Amount')


class RefundForm(forms.Form):
    form_payment_id = forms.IntegerField(widget=forms.HiddenInput)
    form_amount = forms.FloatField(widget=forms.HiddenInput)


class PaymentCreditCardForm(forms.Form):
    cardholder_name = forms.CharField(max_length=50, required=True, label=_(u"Cardholder name"))
    card_number = forms.CharField(max_length=20, required=True, label=_(u"Card number"))
    card_expiration_date = forms.DateField(input_formats=['%m/%y'], required=True, label=_(u"Credit card expiry date"))
    card_ccv = forms.CharField(max_length=3, required=True, label=_(u"Credit Card Verification"))
    accepted_terms_conditions = forms.BooleanField(
        required=True,
        label=_(u"I accept the general sales conditions *")
    )

payments/views.py
# -*- coding: utf-8 -*-


import payplug
import rollbar

from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from django.core.mail import send_mail
from django.template.loader import render_to_string

from lingerie_project import settings

from .models import CreditCard, Payment, ClientChargeAmount
from .forms import PaymentCreditCardForm, AdminPaymentForm, RefundForm


def paid(request, payment):
    payment_id = str(payment.id)
    payment_state = str(payment.is_paid)
    payment_amount = str(payment.amount)

    local_payment_id = payment.metadata['local_payment_id']
    payment_db = Payment.objects.get(id=local_payment_id)

    # print "Card is saved?:", str(resource.save_card)
    # print "Card Id is:", str(resource.card.id)

    if payment.save_card:
        card_id = str(payment.card.id)
        card_exp_month = str(payment.card.exp_month)
        card_exp_year = str(payment.card.exp_year)
        card = CreditCard.objects.get_or_create(user=payment_db.user)[0]
        card.card_id = card_id
        card.card_exp_month = card_exp_month
        card.card_exp_year = card_exp_year
        card.save()
    elif payment.is_paid and not payment.hosted_payment:
        card_id = str(payment.card.id)
        card = CreditCard.objects.get_or_create(user=payment_db.user)[0]
        card.card_id = card_id
        card.save()
    else:
        CreditCard.objects.filter(user=payment_db.user).delete()
        card = None

    payment_db.payment_id = payment_id
    payment_db.payment_amount = payment_amount
    payment_db.payment_state = payment_state
    payment_db.credit_card = card
    payment_db.status = 2
    payment_db.save()


def error_pay(request, payment):
    local_payment_id = payment.metadata['local_payment_id']
    payment_db = Payment.objects.get(id=local_payment_id)
    payment_db.status = 3
    payment_db.save()


@login_required
def index(request):
    payplug.set_secret_key(settings.PAYPLUG_SECRET_KEY)
    client_charge_amount = str(ClientChargeAmount.objects.get())
    if request.POST.get('payplugToken'):
        credit_card_form = PaymentCreditCardForm(request.POST)
        if credit_card_form.is_valid():
            payment_obj = Payment.objects.create(amount=client_charge_amount,
                                                 user=request.user,
                                                 currency='EUR',
                                                 status=0,
                                                 type=0)
            payment_data = {
                'amount': get_amount(client_charge_amount),
                'currency': 'EUR',
                'payment_method': request.POST.get('payplugToken'),
                'customer': {
                    'email': request.user.email,
                    'first_name': request.user.first_name,
                    'last_name': request.user.last_name,
                },
                'save_card': True,
                'metadata': {
                    'local_payment_id': payment_obj.id
                },
            }

            payment = payplug.Payment.create(**payment_data)
            if payment.is_paid:
                paid(request, payment)

                payload = {
                    "customer_name": request.user.first_name,
                }

                html_message_to_send = render_to_string('lingerie_app/email/thanks_after_payments.html', context=payload)
                txt_message_to_send = render_to_string('lingerie_app/email/thanks_after_payments.txt', context=payload)
                try:
                    send_mail(
                        subject=u'Votre commande de Box Lingerie a bien été validée, merci pour votre confiance !',
                        from_email=settings.DEFAULT_FROM_EMAIL,
                        recipient_list=[request.user.email],
                        # recipient_list=[settings.EMAIL_HOST_USER, "genevieve@miroirdemuses.com"],
                        message=txt_message_to_send,
                        html_message=html_message_to_send,
                        fail_silently=False
                    )
                except Exception as err:
                    rollbar.report_message(err.message)

                return render(request, "payments/return.html")
            else:
                error_pay(request, payment)
                return render(request, "payments/cancel.html")
    else:
        credit_card_form = PaymentCreditCardForm()
    
    context = {
        'publishable_key': settings.PAYPLUG_PUBLISH_KEY,
        'form': credit_card_form,
        'payplug_amount': get_amount(client_charge_amount),
        'frontend_amount': client_charge_amount  # This amount for notifying user about his charging. Done in case of.
    }
    return render(request, 'payments/index.html', context)


def payments_return(request):
    return render(request, 'payments/return.html')


def payments_cancel(request):
    return render(request, 'payments/cancel.html')


def refund(request, payment):
    payment_id = str(payment.id)
    payment_state = 2
    payment_amount = str(payment.amount)

    local_payment_id = payment.metadata['local_payment_id']
    payment_db = Payment.objects.get(id=local_payment_id)
    payment_db.payment_id = payment_id
    payment_db.payment_amount = payment_amount
    payment_db.payment_state = payment_state
    payment_db.status = 2
    payment_db.save()


@csrf_exempt
def payments_notification(request):
    request_body = request.body
    try:
        resource = payplug.notifications.treat(request_body)
        rollbar.report_message(request_body, level='debug')
        if resource.object == 'refund':
            refund(request, resource)
        elif resource.is_paid:
            paid(request, resource)
            return HttpResponse({"status": "success"})
    except payplug.exceptions.PayplugError as e:
        rollbar.report_message(e, level='debug')


def get_amount(amount):
    return int(int(amount) * 100)


def is_user_super_user(user):
    if user.is_superuser:
        return True
    else:
        return False


@user_passes_test(is_user_super_user, login_url='/accounts/signup/')
def payments_admin(request):
    context = {}
    if request.POST:
        payplug.set_secret_key(settings.PAYPLUG_SECRET_KEY)
        full_host = request.META['HTTP_HOST']
        payment_obj = Payment.objects.create(amount=str(ClientChargeAmount.objects.get()),
                                             user=request.user,
                                             currency='EUR',
                                             status=0)
        if request.POST.get('charge'):
            payment_obj.type = 0
            # charge
            card = CreditCard.objects.get(user=request.POST['user'])
            payment_data = {
                'amount': get_amount(request.POST.get('amount')),
                'currency': 'EUR',
                'payment_method': card.card_id,
                'customer': {
                    'email': request.user.email,
                    'first_name': request.user.first_name,
                    'last_name': request.user.last_name
                },
                'notification_url': 'http://' + full_host + '/payments/payment-notifications/',
                'metadata': {
                    'local_payment_id': payment_obj.id,
                },
            }
            payplug.Payment.create(**payment_data)
            context['type'] = 'charge'
        elif request.POST.get('refund') == 'true':
            payment_obj.type = 1
            # refund
            payment_obj_paid = Payment.objects.get(pk=request.POST.get('form_payment_id'))
            refund_data = {
                'amount': get_amount(request.POST.get('form_amount')),
                'metadata': {
                    'local_payment_id': payment_obj.id,
                    'form_payment_id': request.POST.get('form_payment_id'),
                    'reason': 'The delivery was delayed',
                },
            }
            payplug_payment = payplug.Refund.create(payment_obj_paid.payment_id, **refund_data)
            payment_obj.status = 3
            context['type'] = 'refund'
        payment_obj.save()
    context['payment_list'] = Payment.objects.filter(type=0)
    context['form'] = AdminPaymentForm()
    context['refund_form'] = RefundForm()
    return render(request, 'payments/admin.html', context)

payments/templates/payments/admin.html
{% extends 'lingerie_app/base.html' %}
{% load staticfiles %}

{% block head_title %}
    VOTRE MODE DE PAIEMENT - Lingerie Try & Buy Service
{% endblock %}

{% block content %}
    <section class="return">
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#charge">Charge</a></li>
                <li><a data-toggle="tab" href="#refund">Refund</a></li>
            </ul>

            <div class="tab-content">
                <div id="charge" class="tab-pane fade in active">
                   {% include 'payments/charge.html' %}
                </div>
                <div id="refund" class="tab-pane fade">
                   {% include 'payments/refund.html' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

payments/templates/payments/cancel.html
{% extends 'lingerie_app/base.html' %}
{% load staticfiles %}

{% block head_title %}
    VOTRE MODE DE PAIEMENT
{% endblock %}

{% block content %}
    <section class="cancel">
        <div class="container">
           <div class="col-md-8 col-md-offset-2">
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-success colored">
                        Votre paiement a malheureusement échoué. Pour toute question, n'hésitez pas à nous contacter à l'adresse e-mail suivante : <a href="mailto:contact@miroirdemuses.com">contact@miroirdemuses.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

payments/templates/payments/charge.html
<h3>CHARGE</h3>
    <form action="{% url 'payments_admin' %}" method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {# Include the visible fields #}
    {% for field in form.visible_fields %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    <input type="submit" name="charge" value="Charge" />
</form>

payments/templates/payments/index.html
{% extends 'lingerie_app/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block head_title %}
    Finalisez votre commande
{% endblock %}

{% block content %}
    <script src="{% static "js/jquery.maskedinput.js" %}" type="text/javascript"></script>
    <script type="text/javascript" src="https://api.payplug.com/js/1.0/payplug.js"></script>
    <script type="text/javascript">
        Payplug.setPublishableKey('{{ publishable_key }}');

        var payplugResponseHandler = function(code, response, details) {
            console.log(code + ' : ' + response + ' : ' + details);
            if (code == 'card_number_invalid') {
                document.querySelectorAll("#error-card-bad")[0].style.display = 'block';
            }
            if (code == 'cvv_invalid') {
                document.querySelectorAll("#error-cvv-bad")[0].style.display = 'block';
            }
            if (code == 'expiry_date_invalid') {
                document.querySelectorAll("#error-expiry-bad")[0].style.display = 'block';
            }
            if (code == 'payplug_api_error') {
                document.querySelectorAll("#error-api-bad")[0].innerHTML = response + ', details: ' +  details;
                document.querySelectorAll("#error-api-bad")[0].style.display = 'block';
            }
            return false;
        };

        document.addEventListener('DOMContentLoaded', function() {
            [].forEach.call(document.querySelectorAll("[data-payplug='form']"), function(el) {
                el.addEventListener('submit', function(event) {
                    var form = document.querySelectorAll("#paymentForm")[0];
                    Payplug.card.createToken(form, payplugResponseHandler,
                        {
                            'amount': {{ payplug_amount }},
                            'currency': 'EUR'
                        });
                    event.preventDefault();
                })
            })
        });
        {#    Masked inputs #}
        $(function($){
            $("#id_card_number").mask("9999 9999 9999 9999", {placeholder:" "});
            $("#id_card_expiration_date").mask("99/99", {placeholder:" "});
            $("#id_card_ccv").mask("999?9", {placeholder:" "});
        });
        // {# Debugging. Remove after...   #}
        // $(document).ready(function() {
        //     $(".form-to-action-btn").click(function () {
        //         console.log($("#id_card_expiration_date").val());
        //     });
        // });
    </script>

    <section class="payment colored">
        <div class="container">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-wrapper">

                    <div class="row">
                        <div class="col-md-12">
                            <!-- Some little changes by Adrien -->
                            <div class="section-title">Finalisez votre commande</div>
                            <div class="section-subtitle">Expédition le 12 avril</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="payment-check-marks">
                            <div class="col-md-12">
                                <div class="payment-check-mark"><span>Sans obligation d'achat et sans abonnement</span></div>
                            </div>
                            <div class="col-md-12">
                                <div class="payment-check-mark"><span>Payez les articles conservés au retour de votre box</span></div>
                            </div>
                            <div class="col-md-12">
                                <div class="payment-check-mark"><span>Retours et échanges gratuits - 10 jours pour faire votre choix</span></div>
                            </div>
                            <div class="col-md-12">
                                <div class="payment-check-mark"><span>10€ de frais de conseils et livraison, remboursés dès 100€ d'achat</span></div>
                            </div>
                            <div class="col-md-12">
                                <div class="payment-check-mark"><span>Deuxième sélection envoyée gratuitement si vous n'êtes pas satisfait(e) </span></div>
                            </div>
                        </div>
                    </div>

                    <form action="" method="POST" id="paymentForm" class="form" novalidate data-payplug="form">
                        {% csrf_token %}
                        {#                        <div class="row">#}
                        {#                            <div class="col-md-6">#}
                        {#                                <div class="form-field">#}
                        {#                                    <input type="checkbox" id="checkbox-0" /><label for="checkbox-0">J’ai un bon de réduction</label>#}
                        {#                                    <input type="text" placeholder="" />#}
                        {#                                </div>#}
                        {#                            </div>#}
                        {#                        </div>#}
                        <div class="input-error-wrapper" id="error-api">
                            <p class="input-error" id="error-api-bad"></p>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-field">
                                    <label>{{ form.cardholder_name.label }}</label>
                                    <label class="label-right lock">{% trans "Secure payment by XX" %}</label>
                                    {{ form.cardholder_name }}
                                    {% for error in form.cardholder_name.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-field"><label>{{ form.card_number.label }}</label>
                                    {{ form.card_number|add_class:"card-input"|append_attr:"data-payplug:card_number"|append_attr:"placeholder:XXXX XXXX XXXX XXXX"}}
                                    {% for error in form.card_number.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="input-error-wrapper" id="error-card">
                                    <p class="input-error" id="error-card-bad" style="display:none;">Numéro de carte invalide.</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-xs-8">
                                <div class="form-field"><label>{{ form.card_expiration_date.label }}</label>
                                    {{ form.card_expiration_date|append_attr:"placeholder:MM/AA"|append_attr:"data-payplug:card_month_year" }}
                                    {% for error in form.card_expiration_date.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="input-error-wrapper" id="error-expiry">
                                    <p class="input-error" id="error-expiry-bad" style="display:none;">Date d expiration incorrecte.</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-xs-8">
                                <div class="form-field"><label>{{ form.card_ccv.label }}</label>
                                    {{ form.card_ccv|append_attr:"placeholder:CVV"|append_attr:"autocomplete:off"|append_attr:"data-payplug:card_cvv" }}
                                    {% for error in form.card_ccv.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="input-error-wrapper" id="error-cvv">
                                    <p class="input-error" id="error-cvv-bad" style="display:none;">Code CVV invalide.</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-field">
                                    {{ form.accepted_terms_conditions }}
                                    <label for="{{ form.accepted_terms_conditions.id_for_label }}">
                                        {{ form.accepted_terms_conditions.label }}
                                    </label>
                                    {% for error in form.accepted_terms_conditions.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-footer">
                                    <p>Vous serez prélevé(e) de 10€ pour la livraison de votre box. Vous n’aurez pas de facturation, ni débit supplémentaires avant d’avoir décidé d’acheter un produit de la sélection proposée.</p>

                                    <p><strong>** Nos contributeurs à la campagne de financement participatif Ulule seront automatiquement remboursés des 10€ de frais de service et livraison. Merci pour votre soutien ! **</strong></p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-to-action-button-wrap">
                                    <button type="submit" class="form-to-action-btn" data-payplug='submit' onclick="track_click()">JE COMMANDE</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <section class="service colored">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-md-6 col-xs-6">

                        <div class="service-secure"><a href="https://www.payplug.com/fr/"><div><span>PAIEMENT</span> 100% Sécurisé</div></a></div>
                    </div>
                    <div class="col-md-6 col-xs-6">
                        <a href="mailto:contact@miroirdemuses.com"><div class="service-client"><div><span>SERVICE CLIENT</span> Besoin d'aide ?<br />Contactez-nous</a></div></div>
            </div>
        </div>
        </div>
        </div>
    </section>

    <!-- Event tracking -->
    <script type="text/javascript">
    function track_click(){

                ga('send', {
          hitType: 'event',
          eventCategory: 'Buttons',
          eventAction: 'click',
          eventLabel: 'Commander'
        });

    }
    </script>

{% endblock %}

payments/templates/payments/refund.html
<script
        src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
<h3>REFUND</h3>
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>User</th>
        <th>Payment Date</th>
        <th>Payment Amount</th>
        <th>Status</th>
        <th>Refund</th>
    </tr>
    </thead>
    <tbody>
    {% for payment in payment_list %}
        <tr>
            <td>{{ payment.id }}</td>
            <td>{{ payment.user.first_name }} {{ payment.user.last_name }}
                <a href="mailto:{{ payment.user.email }}">{{ payment.user.email }}</a></td>
            <td>{{ payment.payment_date }}</td>
            <td>{{ payment.amount }}</td>
            <td>{{ payment.status }}</td>
            <td>
                {% if payment.status == 2 %}
                    <input max="{{ payment.amount }}" type="number" data-id="{{ payment.id }}" class="amount_{{ payment.id }}" name="amount" />
                    <input type="submit" data-payment-id="{{ payment.id }}" class="submit" value="refund" />
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<form method="post" action="" id="payment_form">
    {% for hidden in refund_form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% csrf_token %}
    <input type="hidden" name="refund" value="true"/>
</form>

<script style="text/javascript">
    $( document ).ready(function() {
        $('.submit').on('click', function (e) {
            e.preventDefault();
            var el = $(this),
                payment_id = el.data('payment-id'),
                amount_element = $('body').find('.amount_' + payment_id),
                val = amount_element.val();

            $('#id_form_payment_id').val(payment_id);
            $('#id_form_amount').val(val);
            $('#payment_form').submit();
        });
    });
</script>

payments/templates/payments/refund_form.html
<div class="container-fluid">
        {{ payment.get_refund_form }}
        <input type="submit" name="refund" value="Refund" />
</div>

payments/templates/payments/return.html
{% extends 'lingerie_app/base.html' %}
{% load staticfiles %}

{% block head_title %}
    VOTRE MODE DE PAIEMENT
{% endblock %}

{% block content %}
    <section class="return">
        <div class="container">
            <div class="col-md-8 col-md-offset-2">
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-success colored">
                            <p>Nous avons bien reçu votre paiement et nous vous en remercions.</p>
                            <p>Nous préparons votre box et vous préviendrons de son envoi. Pour toute question, n'hésitez pas à nous contacter à l'adresse e-mail suivante :</p>
                            <p> <strong><a href="mailto:contact@miroirdemuses.com">contact@miroirdemuses.com</a></strong></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}