admin_dashboard_panel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.DashboardIndex.as_view(), name='dashboard_index'),
    url(r'^products/$', views.DashboardProducts.as_view(), name='dashboard_products'),
    url(r'^baskets/$', views.DashboardBaskets.as_view(), name='dashboard_baskets'),
]

lingerie_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.http import HttpResponse


urlpatterns = [
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'', include('lingerie_app.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^payments/', include('payments.urls')),
    url(r'^profiles/', include('profiles.urls')),
    # url(r'^dashboard/', include('admin_dashboard_panel.urls')),
    url(r'^robots.txt', lambda x: HttpResponse("User-agent: *\nDisallow:/admin\nAllow:/", content_type="text/plain"),name="robot_file"),

    # Django admin
    url(r'^admin/', admin.site.urls),
]

payments/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='payments_index'),
    url(r'^payment-return/$', views.payments_return, name='payments_return'),
    url(r'^payment-cancel/$', views.payments_cancel, name='payments_cancel'),
    url(r'^payment-notifications/$', views.payments_notification, name='payments_notification'),
    url(r'^payment-admin/$', views.payments_admin, name='payments_admin')
]

admin_dashboard_panel/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

payments/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _
from django.db.models.signals import post_save
from django.dispatch import receiver

from products_catalog.models import Product


class CreditCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card_id = models.CharField(max_length=256, null=False)
    card_exp_month = models.CharField(max_length=2, null=False)
    card_exp_year = models.CharField(max_length=4, null=False)

    def __unicode__(self):
        return unicode(self.card_id)

    def __str__(self):
        return str(self.card_id)


class Payment(models.Model):
    user = models.ForeignKey(User)
    credit_card = models.ForeignKey(CreditCard, null=True)
    processing_start_date = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField(default=0)
    currency = models.CharField(max_length=5, null=False, default='EUR')
    payment_id = models.CharField(max_length=256)
    payment_state = models.CharField(max_length=256)
    payment_date = models.DateTimeField(null=True, auto_now_add=True)
    # Status
    STATUS = (
        (0, _('New')),
        (1, _('Sent for processing')),
        (2, _('Payed')),
        (3, _('Error'))
    )
    # 0 - new
    # 1 - sent for processing
    # 2 - payed
    # 3 - error
    status = models.PositiveIntegerField(choices=STATUS, default=0, blank=False)
    TYPES = (
        (0, _('Charge')),
        (1, _('Refund'))
    )
    type = models.PositiveIntegerField(choices=TYPES, default=0, blank=False)


class ClientChargeAmount(models.Model):
    amount_to_charge = models.IntegerField(verbose_name=_('client charge amount'), unique=True)

    def __unicode__(self):
        return unicode(self.amount_to_charge)

    def __str__(self):
        return str(self.amount_to_charge)


class Basket(models.Model):
    payment = models.ForeignKey(Payment, related_name='payment')
    STATUS = (
        (0, _('shopping	time')),
    )
    status = models.PositiveIntegerField(choices=STATUS, default=0, blank=False)
    products = models.ManyToManyField(Product, blank=True)

    def __unicode__(self):
        return unicode('Basket for {} {}'.format(self.payment.user.first_name, self.payment.user.last_name))

    def __str__(self):
        return str('Basket for {} {}'.format(self.payment.user.first_name, self.payment.user.last_name))


@receiver(post_save, sender=Payment)
def create_user_basket(sender, instance, **kwargs):
    Basket.objects.get_or_create(
        payment=instance,
        status=0
    )

admin_dashboard_panel/views.py
from payments.models import Payment, Basket
from products_catalog.models import Product

from django.shortcuts import render
from django.views.generic import ListView


class DashboardIndex(ListView):
    template_name = 'admin_dashboard_panel/index.html'
    context_object_name = 'payments_list'
    paginate_by = 10
    queryset = Payment.objects.order_by('-pk')

    # TODO: Add pagination div into index.html template


class DashboardProducts(ListView):
    template_name = 'admin_dashboard_panel/products_list.html'
    context_object_name = 'products_list'
    paginate_by = 10
    queryset = Product.objects.order_by('-pk')

    # TODO: Add pagination div into products_list.html template


class DashboardBaskets(ListView):
    template_name = 'admin_dashboard_panel/baskets_list.html'
    context_object_name = 'baskets_list'
    paginate_by = 10
    queryset = Basket.objects.order_by('-pk')

    # TODO: Add pagination div into baskets_list.html template

admin_dashboard_panel/templates/admin_dashboard_panel/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <title>
        {% block head_title %}
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Lingerie Try&Buy</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">

                {% if request.path == '/dashboard/' %}
                    <li class="active"><a href="{% url 'dashboard_index' %}">Overview <span class="sr-only">(current)</span></a></li>
                {% else %}
                    <li><a href="{% url 'dashboard_index' %}">Overview</a></li>
                {% endif %}
                <li><a href="#">SomeLink2</a></li>
                <li><a href="#">SomeLink3</a></li>
                <li><a href="#">SomeLink4</a></li>
            </ul>

            <ul class="nav nav-sidebar">
                {% if request.path == '/dashboard/baskets/' %}
                    <li class="active"><a href="{% url 'dashboard_baskets' %}">Baskets</a></li>
                {% else %}
                    <li><a href="{% url 'dashboard_baskets' %}">Baskets</a></li>
                {% endif %}
            </ul>

            <ul class="nav nav-sidebar">
                {% if request.path == '/dashboard/products/' %}
                    <li class="active"><a href="{% url 'dashboard_products' %}">Products</a></li>
                {% else %}
                    <li><a href="{% url 'dashboard_products' %}">Products</a></li>
                {% endif %}
            </ul>
        </div>

        {% block content %}
        {% endblock %}

    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery.min.js'%}"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery.min.js'%}"><\/script>')</script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
</body>
</html>

admin_dashboard_panel/templates/admin_dashboard_panel/baskets_list.html
{% extends 'admin_dashboard_panel/base.html' %}
{% load staticfiles %}

{% block head_title %}
    Baskets - Dashboard Miroir de Muses
{% endblock %}


{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Products - Dashboard</h1>
        <h2 class="sub-header">Products database</h2>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Basket username</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for basket in baskets_list %}
                <tr>
                    <td>{{ basket.id }}</td>
                    <td>{{ basket }}</td>
                    <td>{{ basket.get_status_display }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

admin_dashboard_panel/templates/admin_dashboard_panel/index.html
{% extends 'admin_dashboard_panel/base.html' %}
{% load staticfiles %}

{% block head_title %}
    Dashboard - Miroir de Muses
{% endblock %}


{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Dashboard</h1>

{#        <div class="row placeholders">#}
{#            <div class="col-xs-6 col-sm-3 placeholder">#}
{#                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">#}
{#                <h4>Label</h4>#}
{#                <span class="text-muted">Something else</span>#}
{#            </div>#}
{#            <div class="col-xs-6 col-sm-3 placeholder">#}
{#                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">#}
{#                <h4>Label</h4>#}
{#                <span class="text-muted">Something else</span>#}
{#            </div>#}
{#            <div class="col-xs-6 col-sm-3 placeholder">#}
{#                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">#}
{#                <h4>Label</h4>#}
{#                <span class="text-muted">Something else</span>#}
{#            </div>#}
{#            <div class="col-xs-6 col-sm-3 placeholder">#}
{#                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">#}
{#                <h4>Label</h4>#}
{#                <span class="text-muted">Something else</span>#}
{#            </div>#}
{#        </div>#}

        <h2 class="sub-header">Payed subscriptions</h2>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Customer name</th>
                    <th>Processing start date</th>
                    <th>Amount</th>
                    <th>Payment state</th>
                    <th>Status</th>
                    <th>Type</th>
                </tr>
                </thead>
                <tbody>
                {% for payment in payments_list %}
                <tr>
                    <td>{{ payment.id }}</td>
                    <td>{{ payment.user.first_name }} {{ payment.user.last_name }}</td>
                    <td>{{ payment.processing_start_date }}</td>
                    <td>{{ payment.amount }}</td>
                    <td>{{ payment.payment_state }}</td>
                    <td>{{ payment.get_status_display }}</td>
                    <td>{{ payment.get_type_display }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

admin_dashboard_panel/templates/admin_dashboard_panel/products_list.html
{% extends 'admin_dashboard_panel/base.html' %}
{% load staticfiles %}

{% block head_title %}
    Products - Dashboard Miroir de Muses
{% endblock %}


{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Products - Dashboard</h1>
        <h2 class="sub-header">Products database</h2>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Reference code</th>
                    <th>Purchasing price</th>
                    <th>MDM price</th>
                    <th>Cat budget</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products_list %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.reference_code }}</td>
                    <td>{{ product.purchasing_price }}</td>
                    <td>{{ product.mdm_price }}</td>
                    <td>{{ product.cat_budget }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}